apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: docker-node
  template: 
    metatdata:
      labels:
        app: docker-node
    spec: 
      contaner: 
        - name: docker-node-container
          image: askarmadanov/node-app:latest
          port:
            - containerPort: 8080
